services:
  - type: web
    name: brain-tumor-app
    env: python
    buildCommand: |
      unzip brain_tumor_model.zip
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
